In [3]:
import numpy as np

In [12]:
arr1=np.random.rand(5)
arr1

array([0.03879017, 0.15984301, 0.07540659, 0.90414677, 0.0857893 ])

In [17]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr3=np.arange(1,21)
print(arr3)
arr3[5:16]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
arr4=np.linspace(0,1,10)
arr4

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
arr5=np.arange(1,10)
arr5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr5**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])